version: '3.8'

services:
  jupyter-java23:
    build: .
    ports:
      - "8888:8888"
    container_name: jupyter-java23
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.notebook_dir=/home/jovyan/notebooks
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./dist/LambdaCalculusJ.jar:/home/jovyan/java/LambdaCalculusJ.jar
